### ISSUE TITLE
parameter 'service_entry' unrecognized key 'LimitNOFILE'

### ISSUE THREAD

**Issue by alphamonkey79** [voxpupuli/puppet-rabbitmq#1021]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.26.0
- Ruby: ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]
- Distribution: Linux - 4.18.0-553.8.1.el8_10.x86_64
- Module version: 3.7.0

## How to reproduce (e.g Puppet code you use)
module block:
```
  if $facts['kernel'] == 'Linux' {
    systemd::manage_dropin { 'service-90-limits.conf':
      unit                    => "${service_name}.service",
      selinux_ignore_defaults => ($facts['os']['family'] == 'RedHat'),
      service_entry           => {
        'LimitNOFILE'    => $file_limit,
        'OOMScoreAdjust' => $oom_score_adj,
      },
    }
  }
```

## What are you seeing
when attempting to upgrade to module v13.7.0 we are encountering the following in puppet run:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Systemd::Manage_dropin[service-90-limits.conf]: parameter 'service_entry' unrecognized key 'LimitNOFILE'
```
## Output log
```
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Systemd::Manage_dropin[service-90-limits.conf]: parameter 'service_entry' unrecognized key 'LimitNOFILE'
```

**Comment by wyardley** [comment]
What version were you updating from? Is it possible that this is an issue with it pulling in a newer version of https://github.com/voxpupuli/puppet-systemd

**Comment by alphamonkey79** [comment]
That is in fact the exact issue.
We are using an unsupported puppet module for systemd.
We will update this and retry.
Case closed.
Thank you
