### ISSUE TITLE
Quorum Queue Reconciliation Support?

### ISSUE THREAD

**Issue by LangJV** [voxpupuli/puppet-rabbitmq#1029]
I can see that: https://github.com/rabbitmq/rabbitmq-server/pull/8218 Added support for some "quorum queue auto reconciliation parameters" that are disabled by default.

I know this module cannot use the "new" config file (yet) so i traced the schema back and found the "old style" parameters: https://github.com/rabbitmq/rabbitmq-server/blob/658d5b889db426fa1cca390022d39fbcebf94577/deps/rabbit/priv/schema/rabbit.schema#L2598-L2618

However - im not sure how to implement these. Previously, and with other random things I've needed to implement, i was able to simply add it to the "config_additional_variables" section in an open ended HASH. But it's always been a completely "new or separate" config item. Like "rabbitmq_auth_backend_cache", "rabbitmq_auth_backend_http", "rabbitmq_stream", etc.

However for these parameters, they are nested within the "rabbit" section of the configuration, which already seems exclusively controlled by 1:1 puppet parameters set on the "rabbitmq" puppet class when calling it.

Do I need this module modified to support these 5 new parameters on the rabbitmq class? Or is it smart enough that if I add them properly to the "config_additional_variables" segment, it will automatically "compile" the configuration file properly, nesting all the "rabbit" items together intelligently?

I "think" i could likely get it updated to support this, but am hoping i can just feed the info to config_additional_variables and itll just work?

**Comment by wyardley** [comment]
I'm not sure, but my guess is that it won't Just Work automagically.

**Comment by LangJV** [comment]
I started working on something that "might" let it work. It probably doesn't conform to the contribution guidelines yet. I can try to work on that another day/time

https://github.com/voxpupuli/puppet-rabbitmq/pull/1030

**Comment by LangJV** [comment]
Updated, looks to be passing now, think i have tests and reference docs covered. Disclosure, never written spec tests before, did some copy/pasting and i "think" I covered the reasonable combinations of inputs.
