### ISSUE TITLE
rabbitmqadmin fails with puppet 2.7.21 with master  (code from master branch)

### ISSUE THREAD

**Issue by akhil** [voxpupuli/puppet-rabbitmq#121]
I am using vagrant centos 6.2.
When I set puppet to local rabbitmqadmin installs fine.
But when I change it to master it fails.

I can't seem to find any event related to management plugin installation with a master.
But I see the curl command for rabbitmqadmin
Any pointers how I can figure this problem?

**Comment by wyardley** [comment]
I'm guessing this may have since been resolved, it's also tied to a very old Puppet version. I'm going to close this issue.
