### ISSUE TITLE
Allow setting ssl_options, specifically "verify" and "fail_if_no_peer_cert"

### ISSUE THREAD

**Issue by amosshapira** [voxpupuli/puppet-rabbitmq#122]
Currently the ssl options "verify" and "fail_if_no_peer_cert" are wired into the rabbitmq.config template with no way to override their value.

There needs to be a way to provide different values for them.

**Comment by wyardley** [comment]
These appear to have been parameterized for quite some time.

**Comment by amosshapira** [comment]
Thanks for the update
