### ISSUE TITLE
Parameter config_mirrored_queues has no effect

### ISSUE THREAD

**Issue by mgagne** [voxpupuli/puppet-rabbitmq#125]
The parameter `config_mirrored_queues` has no effect when set to true.

Before RabbitMQ 3.0, the HA was controlled by the client when declaring the queue using `x-ha-policy`.

With RabbitMQ 3.0, this behavior is now controlled by a policy on the server side. [1] The HA policy can be applied to specific queues matching a pattern. The HA mode can also be set to different values:
http://www.rabbitmq.com/ha.html#genesis

I therefore don't know how puppetlabs-rabbitmq should implement the parameter `config_mirrored_queues`.

Personally, I create an HA policy (matching my requirements) using a defined resource similar to this one:

``` puppet
define rabbitmq::policy (
  $pattern,
  $definition,
  $vhost    = '/',
  $priority = 0,
) {

  exec { "rabbitmq policy: ${title}":
    command => "rabbitmqctl set_policy -p ${vhost} '${name}' '${pattern}' '${definition}' ${priority}",
    unless  => "rabbitmqctl list_policies | grep -qE '^${vhost}\\s+${name}\\s+${pattern}\\s+${definition}\\s+${priority}$'",
    path    => ['/bin','/sbin','/usr/bin','/usr/sbin'],
    require => Package['rabbitmq-server'],
  }
}
```

``` puppet
node 'rabbitmq.example.org' {
  # ...
  rabbitmq::policy { 'ha-all':
    pattern    => '.*',
    definition => '{"ha-mode":"all","ha-sync-mode":"automatic"}'
  }
}
```

[1] http://www.rabbitmq.com/blog/2012/11/19/breaking-things-with-rabbitmq-3-0/

**Comment by wyardley** [comment]
Appears to not be a parameter anymore, I think this old ticket can be closed out.
