### ISSUE TITLE
rabbitmq clustering status needs manual intervention if cluster partners aren't reachable at time of creation

### ISSUE THREAD

**Issue by evilensky** [voxpupuli/puppet-rabbitmq#130]
This module (and any technique using the rabbitmq config file to set up a cluster) fails if the cluster partners aren'tavailable at the time rabbitmq-server service is started.  Manual intervention is required to clear the node status and create the cluster correctly.

The link below explains this behavior in the 2nd (or third) unquoted paragraph.

[Reference](http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2012-December/024672.html)

**Comment by dn1s** [comment]
I'm working on this issue.
Gonna issue a pr in the next days.

**Comment by dhoppe** [comment]
@evilensky Has this issue been solved by the pull request of @dn1s?
