### ISSUE TITLE
rabbitmqadmin.pp uses the curl command in exec but does not install curl package

### ISSUE THREAD

**Issue by antevens** [voxpupuli/puppet-rabbitmq#142]
On some systems curl is not automatically installed, there should probably be a package dependency on curl being installed.

**Comment by wyardley** [comment]
We are using the archive module now. I will look into whether there's a hard or soft dep already.

**Comment by wyardley** [comment]
from the archive README:

> 
> Users of the module is responsbile for archive package dependencies for
> alternative providers and all extraction utilities such as tar, gunzip, bunzip:
> 
> ```puppet
> if $::facts['osfamily'] != 'windows' {
>   package { 'wget':
>     ensure => present,
>   }
> 
>   package { 'bunzip':
>     ensure => present,
>   }
> 
>   Archive {
>     provider => 'wget',
>     require  => Package['wget', 'bunzip'],
>   }
> }
> ```
