### ISSUE TITLE
Error on using puppet resource rabbitmq_user

### ISSUE THREAD

**Issue by matthewbarr** [voxpupuli/puppet-rabbitmq#147]
Per the docs, you should be able to see the current users with puppet resource rabbitmq_user.

That currently gives an error on both puppet 3.1.1 & 3.3.2:

Error: Could not run: Validation of Rabbitmq_user[guest] failed: must set password when creating user
Wrapped exception:
must set password when creating user
```
Manifest on master:
  class {'::rabbitmq':
}

  rabbitmq_user { 'usernamehere':
    admin    => true,
    password => 'XXXX',
  }
```

**Comment by wyardley** [comment]
I'm able to verify this, even with current master.

**Comment by wyardley** [comment]
https://tickets.puppetlabs.com/browse/MODULES-3084 seems to be the same issue as well.

**Comment by wyardley** [comment]
I think #598 (rework of #460 by @mpolenchuk) might end up fixing this if I can get it to work.

**Comment by wyardley** [comment]
The actual issue seems to be unrelated to those two. It's actually much simpler. The code that's trying to ensure that you don't create a user without defining a password is also preventing `puppet resource rabbitmq_user` from working.

```ruby
  validate do
    if self[:ensure] == :present && !self[:password]
      raise ArgumentError, 'must set password when creating user' unless self[:password]
    end
  end
```

**Comment by wyardley** [comment]
Closing via #598 (I'll cherry-pick the fix for this or break it out into another pull if that doesn't get merged for some reason).
