### ISSUE TITLE
Enabling plugins does not restart the service

### ISSUE THREAD

**Issue by ghola** [voxpupuli/puppet-rabbitmq#148]
In my first puppet run i installed the service and in the second i added the federation plugin, but the server was not restarted and so the plugins not loaded (the rabbit web ui did not show the federation plugin)

**Comment by wyardley** [comment]
FWIW, the plugins in the module itself have a notify of the service:
```
      rabbitmq_plugin { 'rabbitmq_shovel_management':
        ensure   => present,
        notify   => Class['rabbitmq::service'],
        provider => 'rabbitmqplugins',
      }
```
so I think this is a feasible approach when creating plugin resources as well.
