### ISSUE TITLE
'provider rabbitmqplugins not functional on this host'

### ISSUE THREAD

**Issue by haf** [voxpupuli/puppet-rabbitmq#150]
### Problem:

Trying to install a rabbitmq server, most basic variant possible.
### What I do:

``` puppet
include ::rabbitmq
```
### Expected Result

RabbitMQ (+ erlang installs), rabbitmq-server is started, starts listening to the amqp port.
### Actual Result

```
Error: /Stage[main]/Rabbitmq/Rabbitmq_plugin[rabbitmq_management]: Provider rabbitmqplugins is not functional on this host
Warning: /Stage[main]/Rabbitmq::Service/Service[rabbitmq-server]: Skipping because of failed dependencies
Warning: /Stage[main]/Rabbitmq::Install::Rabbitmqadmin/Exec[Download rabbitmqadmin]: Skipping because of failed dependencies
Warning: /Stage[main]/Rabbitmq::Install::Rabbitmqadmin/File[/usr/local/bin/rabbitmqadmin]: Skipping because of failed dependencies
Warning: /Stage[main]/Rabbitmq/Anchor[rabbitmq::end]: Skipping because of failed dependencies
```
### Environment

OS: CentOS 6.4 x86_64
Hypervisor: virtualbox

(::epel is included.)
### Misc Info

`$ rabbitmq-plugin` => command not found

With this there's no problem:

``` yaml
rabbitmq::admin_enable:
  false
```

**Comment by wyardley** [comment]
I think this is not an issue now, though discussing changing the behavior in #570
