### ISSUE TITLE
version parameter does not work

### ISSUE THREAD

**Issue by mattboston** [voxpupuli/puppet-rabbitmq#154]
When using version in the class definition is ignored and the version defined in the config.pp is the one used.

 class { 'rabbitmq':
   version                  => "3.2.2-1",
   config_cluster           => true,
   cluster_nodes            => [ "${rabbitmq_node1}", "${rabbitmq_node2}" ],
   cluster_node_type        => 'disc',
   erlang_cookie            => "${erlang_cookie}",
   wipe_db_on_cookie_change => true,
}

**Comment by wyardley** [comment]
It is misleading, and I've actually taken it out in #493 (the module now just gets the version from status commands, though this could potentially cause some chicken / egg problems). I'm going to mark this as closed, I did try to add some docs mentioning the bit about using `$package_ensure` instead.
