### ISSUE TITLE
RFE: allow $cluster_nodes to be either array or comma-delimited string

### ISSUE THREAD

**Issue by robocoder** [voxpupuli/puppet-rabbitmq#161]
We wanted to parameterize cluster_nodes as a puppet dashboard variable, but the module validation fails (expects array) because puppet dashboard variables are always treated as strings.

**Comment by wyardley** [comment]
I think I'm going to close this one as wont-fix for now; with the switch to Puppet 4 and data types, it seems like it would be kind of backwards to allow both a string / array here, though we can review it if someone wants to submit a PR to add this functionality.
