### ISSUE TITLE
Illegal cluster node name

### ISSUE THREAD

**Issue by thierrymarianne** [voxpupuli/puppet-rabbitmq#163]
I've received this error message while attempting to use rabbitmq module: 

`Error: Illegal name. The given name _cluster_nodes does not conform to the naming rule \A((::)?[a-z0-9]w*)(::[a-z0-9]w*)*\z at /etc/puppet/modules/rabbitmq/manifests/config.pp:45:5`

I've just followed the first basic example as suggested by the documentation : 

```
class { 'rabbitmq':
    service_manage      => false,
    port                => '5672',
    delete_guest_user   => true,
}
```

I've renamed the `$_cluster_nodes` variable to `$cluster_nodes_` both in `rabbitmq.config.erb` and `config.pp`. Is there anything else to do? Is that a proper fix?

**Comment by wyardley** [comment]
Sounds like this was resolved via #160
