### ISSUE TITLE
Make sure to update notes & change log - mange_erlang is no longer present

### ISSUE THREAD

**Issue by matthewbarr** [voxpupuli/puppet-rabbitmq#168]
With a recent change in the git version, you've removed a parameter that was present.  

It's also used in the current version of the puppetlabs-mcollective module, under their middleware manifests (middleware/rabbitmq.pp)

**Comment by wyardley** [comment]
I'm going to close this, since the param has been gone for a while, and so I'm guessing a deprecation warning would no longer be helpful.
