### ISSUE TITLE
Rabbitmq_user_permissions parser fails for empty string

### ISSUE THREAD

**Issue by jmswick** [voxpupuli/puppet-rabbitmq#172]
I'm configuring a 'read_only' user for a rabbitmq setup that only has read only access to a particular vhost.  Using the rabbitmq_user_permissions provider, the module will properly set the permissions for the user, but on subsequent runs it will fail to parse the permissions of the user. 

First run:

```
...
Notice: /Stage[main]/Tmp::Rabbitmq/Rabbitmq_user[read_only]/ensure: created
Notice: /Stage[main]/Tmp::Rabbitmq/Rabbitmq_user_permissions[read_only@/]/ensure: created
```

Second run:

```
Error: /Stage[main]/Tmp::Rabbitmq/Rabbitmq_user_permissions[read_only@/]: Could not evaluate: cannot parse line from list_user_permissions:/            .*
```

This is what I was testing with in a manifest:

``` puppet
  rabbitmq_user { 'read_only':
    admin    => false,
    password => 'ro_pass',
  }

  rabbitmq_user_permissions { 'read_only@/':
    configure_permission => '',
    read_permission      => '.*',
    write_permission     => '',
  }
```

Actual permissions in rabbitmq:

``` shell
[root@vagrant-centos-6 ~]# rabbitmqctl list_user_permissions read_only
Listing permissions for user "read_only" ...
/           .*
...done.
```

Since rabbitmq permissions are regex expressions, the workaround is to use the '^$' regex instead of the empty string ('') permission.  Setting the two empty string permissions in my test case to '^$' in the manifest (and manually on the rabbitmq server) prevents the parser error.  An in-module fix may be to replace empty-string permissions with the '^$' regex before setting it in rabbitmq.

New permissions:

``` shell
[root@vagrant-centos-6 ~]# rabbitmqctl list_user_permissions read_only
Listing permissions for user "read_only" ...
/   ^$  ^$  .*
...done.
```

http://www.rabbitmq.com/access-control.html

**Comment by wyardley** [comment]
Appears to have been fixed in 3985eccb41c00e7ac3bcd40d1814a227c516c294 by @mschuett (mentioned above).
