### ISSUE TITLE
exchanges will be recreated in every puppet run if the vhost is not /

### ISSUE THREAD

**Issue by xcu** [voxpupuli/puppet-rabbitmq#173]
self.instances is executing rabbitmqadmin list exchanges, which uses / by default. If the exchanges are created using another vhost then they won't be included in @property_hash, making the exists method return an incorrect value.

I have created a patch for this which uses rabbitmqctl instead to populate @property_hash (I think that rabbitmqadmin would need the username and password) and it seems to work.

**Comment by wyardley** [comment]
This has been merged, and I don't think affects current master.
