### ISSUE TITLE
invalid parameter provider

### ISSUE THREAD

**Issue by KlavsKlavsen** [voxpupuli/puppet-rabbitmq#49]
I'm getting:

err: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter provider..

From this:
rabbitmq_plugin {'rabbitmq_management':
  ensure => present,
  provider => 'rabbitmqplugins',
}

If I remove the provider - it uses the default (which does nothing but fail :)

I tried (just to test) - to move the rabbitmqplugins.rb to default.rb - but then it just says:
err: Could not find a suitable provider for rabbitmq_plugin

Using puppet-2.7.21 - and just pulled latest puppetlabs-rabbitmq..

Any ideas as to what's up?

**Comment by wyardley** [comment]
Guessing this should be not an issue with any current versions that would get installed? I'm going to close, but re-open if this is still an issue.
