### ISSUE TITLE
add vars to manage management ssl certs separately.

### ISSUE THREAD

**Issue by ninjasloth22** [voxpupuli/puppet-rabbitmq#564]
Add some new vars to specify the management ssl certs separately
Then just default the vars to the current ssl_key/cacert/cert options
e.g 
 {cacertfile, "<%= @management_ssl_cacert %>"},
                  <%- end -%>
                  {certfile, "<%= @management_ssl_cert %>"},
                  {keyfile, "<%= @management_ssl_key %>"}

**Comment by Slm0n87** [comment]
We exactly have the same issue after using ipvs balancing, but still want to be able to access the management console directly on each node.  
If the additional variable was not set, I implemented a fallback to the old variable for backwards compatibility.
