### ISSUE TITLE
Add destination exchange for Shovel

### ISSUE THREAD

**Issue by ibaboo** [voxpupuli/puppet-rabbitmq#565]
Hi 

I would like to add an exchange as a destination for a Shovel however I only see the option for **dest-queue**

My code look like this for a queue. How do I change it for the destination being an exhange?

> 
>       rabbitmq_parameter { 'WorkShovel@/':
>         component_name => 'shovel',
>         value          => {
>           'src-uri'    => $src_uri,
>           'src-queue'  => 'myqueue',
>           'dest-uri'   => 'amqp://',
>           'dest-queue' => 'mydestqueue',
>         },
>

**Comment by wyardley** [comment]
https://www.rabbitmq.com/shovel-dynamic.html suggests `src-exchange` and `dest-exchange`.
This is not something I've worked with personally, but
https://www.rabbitmq.com/shovel-dynamic.html
seems to imply it's supported (at least in the current version).

https://groups.google.com/forum/#!topic/rabbitmq-users/0ArkLBE_0LM 

I did a quick check, though not sure what URIs you're using or how to setup 2 instances quickly in a test environment, but I think the module can support this assuming your RabbitMQ version can, so I'd suggest trying those values and / or posting in a RabbitMQ specific forum if you need more help figuring out how the exchanges should be configured.

**Comment by ibaboo** [comment]
Thank you @wyardley for now I did it manually and not through puppet.
