### ISSUE TITLE
Release puppet/rabbitmq 6.0.0

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-rabbitmq#591]
We want to release the first Voxpupuli `puppet` namespace as soon as possible.  There are a few things we should probably get done first though.

- [x] Add README badges
- [x] modulesync
- [x] Update `Development` section of README
- [x] Update outdated `Apt module compatibility` README section
- [x] Sync labels
- [x] Migrate existing changelog to HISTORY.md
- [x] Tweak Issue/PR titles and labels for better 6.0.0 changelog
- [x] Fix and / or add ignore statements for remaining Rubocop warnings
- [x] Add module to modulesync_config repo
- [x] Add module to plumbing
- [x] #606 probably should be merged (ideally with tests) first
- [x] Investigate #611

**Comment by alexjfisher** [comment]
@wyardley @bastelfreak Can you think of anything else we need to do before the release?

**Comment by wyardley** [comment]
Sounds  about right to me. We'll also need to do some combination of suppressing / fixing the 'multiple expectations' warnings. There are a few that I think I can resolve, but then we should set a Rubocop ignore for the rest, and open an issue to fix them eventually.

I'd love to switch to archive module, but agree with @alexjfisher that we can wait on that for the next release.

**Comment by wyardley** [comment]
I think README badges are good now, and I synced the labels and checked that off.

**Comment by wyardley** [comment]
Created #596, let me know how that looks

**Comment by wyardley** [comment]
#597 addresses changelog

**Comment by wyardley** [comment]
Realized that https://github.com/voxpupuli/plumbing/pull/136 already existed after I submitted https://github.com/voxpupuli/plumbing/pull/137.
However, someone with the Travis password will need to add that.

**Comment by wyardley** [comment]
Got #602 open, and created #603 as a reminder to eventually fix.

**Comment by costela** [comment]
after some delay (sorry! :sweat_smile:) I got #609 fixed (resub of #606).
