### ISSUE TITLE
Look into "error while resolving custom fact" error

### ISSUE THREAD

**Issue by wyardley** [voxpupuli/puppet-rabbitmq#614]
As discussed in #611, should look into making the module more tolerant in cases where custom facts don't exist.

```
Error: Facter: error while resolving custom fact "rabbitmq_nodename": undefined method[]' for nil:NilClass`
```

**Comment by wyardley** [comment]
thanks to @dhollinger for pointing out the typo with Resolution vs Execution.

**Comment by wyardley** [comment]
I think #615 will resolve this

**Comment by ldh761** [comment]
问下这个问题解决了吗？是怎么处理的，盼回复

**Comment by wyardley** [comment]
@ldh761 应该是
