### ISSUE TITLE
revert 8e97331df46b6123d3813d9eaf9fcbcf50e62c59

### ISSUE THREAD

**Issue by trefzer** [voxpupuli/puppet-rabbitmq#634]
commit 8e97331df46b6123d3813d9eaf9fcbcf50e62c59 added a newline in
the ssl configuration of rabbitmqadmin. 
with the empty line in the config, the following errors occur in the log when trying to download rabbitmqadmin.

=ERROR REPORT==== 14-Sep-2017::11:25:51 ===
    application: mochiweb
    "Accept failed error"
    "{error,{options,{keyfile,\"*blah*_privkey.pem\",\n                         {error,eacces}}}}"

Rabitmq Version: 3.6.5, on CentOs 7.3

**Comment by wyardley** [comment]
@trefzer I noticed this when testing #632 and updated it (it was initially a single commit, but I squashed it into some bigger changes; if I had realized a bug, probably would have left it separate to make it more obvious). 
So the changeset in
https://github.com/voxpupuli/puppet-rabbitmq/pull/632/commits/d66d0d82e65e764a7edac5c379598144bab1a5c7 should fix this.
We'll be cutting 7.0.0 soon.
