### ISSUE TITLE
Add variable to rabbitmq.config

### ISSUE THREAD

**Issue by Minastirith** [voxpupuli/puppet-rabbitmq#644]
Hello,

could it be possible to add some variables in the class rabbitmq please ? I have the need to set them and I can't find it in the module.

$vm_memory_high_watermark            = $rabbitmq::vm_memory_high_watermark
$disk_free_limit                                    = $rabbitmq::disk_free_limit 

Regards.

**Comment by wyardley** [comment]
@Minastirith have you seen the `config_additional_variables` parameter? I believe you can use this to set most config variables.
