### ISSUE TITLE
admin_enable throws Server Error: no parameter named 'allow_insecure'

### ISSUE THREAD

**Issue by johnkazmerzak** [voxpupuli/puppet-rabbitmq#646]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.2
- Ruby: ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
- Distribution:
- Module version: puppet/rabbitmq 7.1.0, puppet/archive 2.0.0, puppetlabs/stdlib 4.20.0

## How to reproduce (e.g Puppet code you use)
`admin_enable => true`

## What are you seeing
```
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'allow_insecure' at /local/puppetoss/envs/sst/sstsrdnalin_develop/modules/rabbitmq/manifests/install/rabbitmqadmin.pp
```

**Comment by wyardley** [comment]
Can you verify that you're running puppet/archive 2.0.0 and not one of the other archive modules? Can you post your puppet module list output? This works for me and works in the acceptance tests . I think the param comes from here:

https://github.com/voxpupuli/puppet-archive/blob/dc95b08e349e53eeef50b8f5dcbc9c5cda84e5d3/lib/puppet/type/archive.rb#L232

If I spin up the acceptance test beaker instance with the current version of the module, and your specified version of puppet-archive, I don't get that error.

```
[root@centos-7-x64 tmp]# cat /tmp/apply.pp 
include epel
class { 'rabbitmq':
  admin_enable => true,
}
[root@centos-7-x64 tmp]# puppet apply /tmp/apply.pp 
Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /etc/puppetlabs/puppet/hiera.yaml)
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/modules/rabbitmq/manifests/init.pp", 285]:
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Notice: Compiled catalog for centos-7-x64.axsops.net in environment production in 0.69 seconds
Notice: Applied catalog in 0.48 seconds
[root@centos-7-x64 tmp]# puppet module list | grep archive
├── puppet-archive (v2.0.0)
```

**Comment by johnkazmerzak** [comment]
My apologies for wasting your time. I am no longer able to reproduce the error. I had just upgraded the puppet/archive module from 0.5.1 to 2.0.0 in the Puppetfile and must have still been on 0.5.1 when the error occurred. Thanks!
