### ISSUE TITLE
Error on using puppet resource rabbitmq_binding

### ISSUE THREAD

**Issue by jean-gui** [voxpupuli/puppet-rabbitmq#650]
I'm pretty sure this is the same issue as #147, just for another type.
I also believe most types have a similar issue.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: master: 4.10.8
- Ruby: 2.3.3p222
- Distribution: Debian stretch
- Module version: 7.1.0

## How to reproduce (e.g Puppet code you use)

Run command `puppet resource rabbitmq_binding`

## What are you seeing

Error: Could not run: Validation of Rabbitmq_binding[5538f6c889e4583bace88315c5502438ec434fde8e4f0f200a280c439ace909c] failed: Source and destination must both be defined.

## What behaviour did you expect instead

Get the list of binding resources applied to the host.

**Comment by wyardley** [comment]
@jean-gui This has worked for me in recent memory (at least after I reworked the rabbitmq binding) in #504, maybe I added the validate routine _after_ testing that?

I was able to verify this against 7.1.0 in Beaker; I'll see if just moving that validation piece will fix this one.

**Comment by wyardley** [comment]
@jean-gui I think that fix should resolve your issue. Will try to get it reviewed / merged soon, but feel free to test the changes if you'd like.
