### ISSUE TITLE
RabbitMQ Admin Package should work with Puppet-Archive module, or explicitly depend on camptocamp's archive module

### ISSUE THREAD

**Issue by cmentzer** [voxpupuli/puppet-rabbitmq#658]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: PE 2016.5 - Puppet 4
- Ruby: N/A
- Distribution: RHEL 7 / CentOS 7
- Module version: 8.0.0

## How to reproduce (e.g Puppet code you use)
1. Use the Puppet-archive module 
2. Include the rabbitmq class and allow Puppet to manage it's installation. 

## What are you seeing
Server Error: no parameter named 'allow_insecure' at /etc/puppetlabs/code/environments/rabbitmq/modules/rabbitmq/manifests/install/rabbitmqadmin.pp:45 on Archive[rabbitmqadmin]

## What behaviour did you expect instead
RabbitMQ should download and extract the package using the Archive type provided by https://github.com/voxpupuli/puppet-archive, and should not depend on parameters that exist only in https://github.com/camptocamp/puppet-archive

## Any additional information you'd like to impart

The README specifies that this module depends on https://github.com/voxpupuli/puppet-staging, 
which has been deprecated. 

Code that is causing the problem can be found here: 
https://github.com/voxpupuli/puppet-rabbitmq/blob/09e8af255f2d276c243e8c0d43d4032a2ebc18ff/manifests/install/rabbitmqadmin.pp#L45

**Comment by wyardley** [comment]
FWIW, this module uses the Vox puppet-archive (as you'd expect), and is tested against that, not the Camptocamp module.

I have not seen the error you're seeing; which version of puppet-archive are you using?
https://github.com/voxpupuli/puppet-archive/blob/dc95b08e349e53eeef50b8f5dcbc9c5cda84e5d3/lib/puppet/type/archive.rb#L232-L235

I opened #660 to update the README (though `metadata.json` has the correct dependency).

**Comment by cmentzer** [comment]
Seems like it was my mistake, the problem was simply that the feature branch was using the correct version of puppet-archive (2.1.0), but the MoM (production branch) was still using an older version of the module. Hence the "Server Error" portion of the error message.
