### ISSUE TITLE
puppet/rabbitmq 8.0.0 - /etc/apt/sources.list.d/rabbitmq.list not updated/created

### ISSUE THREAD

**Issue by cristianbalan-mf** [voxpupuli/puppet-rabbitmq#662]
Switching from puppetlabs/rabbitmq **5.6.0** to puppet/rabbitmq **8.0.0** works fine on _existing instance_ (Ubuntu 14.04 Trusty) but If I start with a _new instance_ (same OS), Puppet fails. Creating a new instance while switching back to **5.6.0**, works just fine.

I found that with **8.0.0**, the `/etc/apt/sources.list.d/rabbitmq.list` is not being created and as such, `rabbitmq-server` is installed from the OS repo (a very old **3.2.4-1ubuntu0.1**) rather than what it should be according to https://github.com/voxpupuli/puppet-rabbitmq/blob/master/manifests/repo/apt.pp. Creating manually the `/etc/apt/sources.list.d/rabbitmq.list` and running `apt-get update`, Puppet completes its job perfectly as is installing the latest package.

Also, I saw that, on _existing instance_, running puppet/rabbitmq **8.0.0** does not update `/etc/apt/sources.list.d/rabbitmq.list`, so it stays with the "old" repo:
> deb http://www.rabbitmq.com/debian/ testing main

My puppetlabs/apt is on 2.4.0 but even updating to 4.3.0 doesn't help.

Any thoughts?

**Comment by wyardley** [comment]
Are you using `repos_ensure => true` (default false)?
Take a look at the breaking changes listed in https://github.com/voxpupuli/puppet-rabbitmq/blob/master/CHANGELOG.md (this one is in 6.0.0).

**Comment by cristianbalan-mf** [comment]
I'm using neither `repos_ensure` nor `manage_repos` I'm afraid.

**Comment by wyardley** [comment]
@cristianbalan-mf Glad you got it working. Sorry if I wasn't clear. The breaking change _was_ that the module used to use the RabbitMQ package as the default, and now uses vendor (i.e., OS) one by default. So you didn't need `repos_ensure` to get that version with 5.6.x, but you do from 6.0.0 on. IIRC, `manage_repos` is now gone or deprecated.
