### ISSUE TITLE
How to install custom plugins label:question

### ISSUE THREAD

**Issue by jjuarez** [voxpupuli/puppet-rabbitmq#697]
Hi,

is there a clear way to install custom plugins?, Let me elaborate a bit our scenario; We're working with the MQTT plugin but our rabbitMQ instances need an special plugin, I would be enough to copy the file into the plugins directory and activate it with the rabbitmq_plugin resource?

thanks in advance,
Javier

**Comment by jjuarez** [comment]
For now I'm trying to install the plugin file as another file resource and activate it through the rabbitmq_plugin resource, without success, any idea will be welcome

**Comment by wyardley** [comment]
I can see if I can still find how I did something like this in the past. Does dropping the file in place and restarting the service pick it up?

IIRC, you can just drop in the .ez file https://www.rabbitmq.com/installing-plugins.html

**Comment by jjuarez** [comment]
We've solved this use case with an ugly workaround, because We needed to install a patched version of the MQTT plugin in our infrastructure (we need to use "." in the topics), mainly based on Debian Stretch, and the OS package didn't help very much, and the plugin is in de core o the rabbitMQ distribution (how about a separate package for the non core plugins?), so after the installation of the package we overwrote the MQTT plugin, I mean the .ez file (packaged by us with the changes... but this is another story), and activate this patched plugin with the puppet module resource rabbitmq_plugin, and yes, it works.

But it would be a nice idea to get the possibility of install this kind of plugins extending the interface of the puppet type rabbitmq_plugin with a file parameter, for example, because we have to install the HTTP backend auth, which is not part of the core with the same dirty method
