### ISSUE TITLE
Can't connect to IPv4 Address

### ISSUE THREAD

**Issue by mattboston** [voxpupuli/puppet-rabbitmq#701]
## Affected Puppet, Ruby, OS and module versions/distributions
- Puppet Server: CentOS 7
- Client Server: Amazon Linux 2 (2017.12)
- Puppet: puppetserver-2.8.1-1.el7.noarch
- Foreman: foreman-1.16.0-1.el7.noarch
- Ruby: 2.1.9
- Module version: 8.2.2

## Config
```puppet
class { '::rabbitmq':
  config_cluster                  => true,
  cluster_nodes                   => ['opstest-mq001','opstest-mq002'],
  cluster_node_type               => 'ram',
  erlang_cookie                   => "${erlang_cookie}",
  wipe_db_on_cookie_change        => true,
  delete_guest_user               => true,
  port                            => 5672,
  management_ip_address           => '0.0.0.0',
}
```
## Config Generated
```
% This file managed by Puppet
% Template Path: rabbitmq/templates/rabbitmq.config
[
  {rabbit, [
    {cluster_nodes, {['rabbit@opstest-mq001', 'rabbit@opstest-mq002'], ram}},
    {cluster_partition_handling, ignore},
    {tcp_listen_options, [
         {backlog,       128},
         {nodelay,       true},
         {linger,        {true, 0}},
         {exit_on_close, false}
    ]},
    {default_user, <<"guest">>},
    {default_pass, <<"guest">>}
  ]},
  {kernel, [
    
  ]}
,
  {rabbitmq_management, [
    {listener, [
      {ip, "0.0.0.0"},
      {port, 15672}
    ]}
  ]}
].
% EOF
```

## Netstat Output
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      24476/beam.smp      
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      24310/epmd          
tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      24476/beam.smp      
tcp6       0      0 :::5672                 :::*                    LISTEN      24476/beam.smp      
tcp6       0      0 :::4369                 :::*                    LISTEN      24310/epmd          
```
## Nmap Output
```
nmap -sT opstest-mq001       

Starting Nmap 6.40 ( http://nmap.org ) at 2018-04-26 15:38 UTC
Nmap scan report for opstest-mq001 (10.10.178.156)
Host is up (0.0047s latency).
rDNS record for 10.10.178.156: ip-10-10-178-156.ec2.internal
Not shown: 997 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
111/tcp  open  rpcbind
5666/tcp open  nrpe
```

## What are you seeing
For some reason when Rabbit gets installed and starts up, it brings up all ports on IPv4 addresses with the exception of 5672, which it brings up on IPv6.  We don't use IPv6 and have no configurations in Puppet to define any IPv6 configurations.  The network interface does have an IPv6 address, but nowhere have we defined anything to say that it's used.  What should be changed in my Puppet config to have that port brought up on the IPv6 interface?

**Comment by dn1s** [comment]
Is `$ipv6` set to `false` in rabbitmq::params and was not overwritten somewhere?

**Comment by mattboston** [comment]
It's set to false.  Where else would it be set?

# grep ipv6 params.pp 
  $ipv6                                = false

**Comment by wyardley** [comment]
Edited the post just to put some of the output into fixed width. I don't have any answers for you, but I do remember coming across some quirks along these lines when I was working on the acceptance tests, and just more generally when I was running RabbitMQ.

Which RabbitMQ version are you using?

**Comment by wyardley** [comment]
I notice you have `management_ip_address` explicitly set; does setting this param change anything for you?
https://github.com/voxpupuli/puppet-rabbitmq/blob/v8.2.2/manifests/init.pp#L134-L135

**Comment by mattboston** [comment]
Somewhere I saw mention of management_ip_address, so decided to try that, as well as specifying port.  I just tried node_ip_address => '0.0.0.0' and that moved port 5672 over to tcp. Here's the results of netstat now.

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      3148/beam.smp       
tcp        0      0 0.0.0.0:5672            0.0.0.0:*               LISTEN      3148/beam.smp       
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      3148/beam.smp       
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      3173/epmd           
tcp6       0      0 :::61613                :::*                    LISTEN      3148/beam.smp       
tcp6       0      0 :::4369                 :::*                    LISTEN      3173/epmd           

But now I'm getting the following error when trying to connect.  Please note, the host in my tests is using a fully qualified domain in the actual script.  I should also note, I have older infrastructure (older puppet server, older module puppetlabs-rabbitmq(4.0.0), older server, with older rabbitmq 3.2.0-1), this was working on.  I created a new puppet/foreman, new rabbit server and copied over the puppet config.

#error message
pika.exceptions.IncompatibleProtocolError: (-1, "error(104, 'Connection reset by peer')")

#test script to see if rabbit is working

import pika, time

host = 'opstest-mq001'
credentials = pika.PlainCredentials('myuser', 'mypass')
connection = pika.BlockingConnection(
    pika.ConnectionParameters(
        host=host,
        socket_timeout=300,
        heartbeat=10,
        credentials=credentials,
    )   
)
channel = connection.channel()

channel.queue_declare(queue='task_queue', durable=True)
print(' [*] Waiting for messages. To exit press CTRL+C')

def callback(ch, method, properties, body):
    ch.basic_ack(delivery_tag = method.delivery_tag)

channel.basic_qos(prefetch_count=1)
channel.basic_consume(callback,
    queue='task_queue')

**Comment by nick-dasilva** [comment]
Hi, I ran into a similar issue with a standalone/single-node config, also on CentOS 7.  The issue appears to be a buggy combination of RabbitMQ and Erlang versions available in the EPEL repository.

I was able to work around the problem by setting the rabbitmq class's $repos_ensure parameter to "true," as well as manually importing the "official" Erlang distribution repos from the [RabbitMQ Erlang RPM project](https://github.com/rabbitmq/erlang-rpm) in my manifest.

Whatever was breaking before seemed to be specific to RabbitMQ v3.3.x and Erlang R16B03, both of which are supplied via EPEL.  After replacing the EPEL versions with the latest from RabbitMQ, forcing the node_ip_address to an IP4 value (management_ip_address and management_port didn't matter), I am able to connect from Spring AMQP. I also no longer get an almost immediate terminated connection when attempting to connect.

Try putting this in your node manifest, removing all Erlang and RabbitMQ packages from the server, and performing a Puppet run:

    yumrepo { 'rabbitmq_erlang':
        descr         => 'Latest version of Erlang/OTP for RHEL $releasever - $basearch',
        baseurl       => 'https://packagecloud.io/rabbitmq/erlang/el/7/$basearch',
        enabled       => 1,
        gpgcheck      => 1,
        gpgkey        => 'https://packagecloud.io/rabbitmq/erlang/gpgkey',
        priority      => 1,
    }

    yumrepo { 'rabbitmq_erlang-source':
        descr         => 'Latest version of Erlang/OTP sources for RHEL $releasever - $basearch',
        baseurl       => 'https://packagecloud.io/rabbitmq/erlang/el/7/SRPMS',
        enabled       => 1,
        gpgcheck      => 1,
        gpgkey        => 'https://packagecloud.io/rabbitmq/erlang/gpgkey',
        priority      => 1,
    }

Also note that the $ipv6 parameter doesn't seem to affect the default IP binding as of module version 8.4.0.

**Comment by wyardley** [comment]
Thanks @nick-dasilva 
The current README and code probably doesn't do the right thing around Erlang anymore. I don't have time to devote to it, but feel free to submit PRs about either code changes or docs changes to make some of this easier.

I think the erlang module we're using is more or less abandoned.
