### ISSUE TITLE
no parameter named 'download_option' 

### ISSUE THREAD

**Issue by wikimatze** [voxpupuli/puppet-rabbitmq#706]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.2
- Ruby: 2.3
- Distribution: Ubuntu 16.04
- Module version: 8.2.0

## What are you seeing

`Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'download_options' at /opt/puppetforge/modules/rabbitmq/manifests/install/rabbitmqadmin.pp:45 on Archive[rabbitmqadmin] at /opt/puppetforge/modules/rabbitmq/manifests/install/rabbitmqadmin.pp:45 on node dev-matze.wikimatze.net`

## What behaviour did you expect instead

No error :smiley_cat: 

## Output log

see chapter 'What are you seeing'

## Any additional information you'd like to impart

We have puppet-archive 3.0.0

**Comment by wikimatze** [comment]
My "solution" so far:

```puppet
    archive { 'rabbitmqadmin':
      path             => "${rabbitmq::rabbitmq_home}/rabbitmqadmin",
      source           => "${protocol}://${sanitized_ip}:${management_port}/cli/rabbitmqadmin",
      username         => $default_user,
      password         => $default_pass,
      allow_insecure   => true,
      #download_options => $archive_options,
      cleanup          => false,
      require          => [
        Class['rabbitmq::service'],
        Rabbitmq_plugin['rabbitmq_management']
      ],
    }
```

I have checked the files of could find that the archive_options are just fine defined (like you mentioned in your PR)

**Comment by wyardley** [comment]
Ah I see, Yeah, we're passing `archive_options` to the archive module's `download_options`.
What does `puppet module list` show? Is it possible you have a competing archive module like the camptocamp one?

**Comment by wikimatze** [comment]
I'm currently living with that 'solution' - other things were not working.

**Comment by tardoe** [comment]
I'm having a similar issue - no other competing modules.

Puppet 4.10.12
Module Version: 8.2.2

**Comment by wyardley** [comment]
Can folks having problems confirm the archive module you’re using (name and version)

**Comment by mjrasobarnett** [comment]
I had this problem as well, but I was using an older version of puppet-archive (https://github.com/voxpupuli/puppet-archive) - I used version v1.3.0.

Looking through the commits for puppet-archive, it looks like the download_options param on the archive type only got added from release v2.0.0 onwards. 

I upgraded puppet-archive in my environment to version 2.0.0 and I can confirm that this fixes this issue.

The metadata.json for this module lists puppet-archive dependency as compatible with version: >= 1.0.0, which is wrong I believe on account of this issue. I think it should be changed to be >= 2.0.0 (at least from my experience testing with Centos 7).

**Comment by wyardley** [comment]
@mjrasobarnett thanks! that's very useful information. I'll throw up a PR to update the metadata!

**Comment by wyardley** [comment]
It's interesting that the OP has `puppet-archive 3.0.0`. That said, I hope the PR should help avoid this situation for most users?

**Comment by mjrasobarnett** [comment]
Actually there could be another element to this, as looking closer at my own set up I'm seeing occasional re-occurrences of this error even after updating the puppet-archive module.

However, in my own case, I believe what I'm seeing is because of this: https://puppet.com/docs/puppet/5.3/environment_isolation.html  ( I don't yet do the r10k recommendations in that article...)

since I am testing this module in a puppet environment, and I have puppet-archive installed (at version v1.3.0) on my production and other pre-existing puppet environments. So I think this older version of the 'archive' ruby resource type is occasionally leaking due to this problem. It would explain what I was seeing where one puppet compile would fail with the same error as OP, and then the next compile would complete successfully.

In any case, I can't speak for the OP, but I just tested puppet-archive v3.0.0 in my environment and it works fine with this module, so I don't believe there is any problem with this module other than the metadata.json fix you've made.

**Comment by wyardley** [comment]
@mjrasobarnett I have had that issue in the past as well (when using "environments" to manage multiple archive environments). The default one needs to get loaded (by a client) first, or you end up with caching issues.

**Comment by alexizmailov** [comment]
Still having this issue on 
- Puppet: v6.0.4
- Ruby: 2.5.0
- Distribution: CentOS Linux release 7.6.1810 (Core)
- Rabbitmq module version: v.9.0.0
- Archive module: v3.2.1

**Comment by sammcj** [comment]
I can confirm this is still occurring as per @alexizmailov states.

@bastelfreak would you rather a new ticket was created for this issue - or simply re-open this issue?

**Comment by sammcj** [comment]
Just found this to now be `download_options` rather than `download_option` - easy fix! :)

**Comment by wyardley** [comment]
@sammcj thanks for looking into this! I think a new issue is a good idea.

Presumably it was `download_option` for some period of time. So probably the fix would need to require >= whatever version that option changed in.

**Comment by alexizmailov** [comment]
Done - https://github.com/voxpupuli/puppet-rabbitmq/issues/790
