### ISSUE TITLE
Fix Beaker test dependency on garethr/erlang

### ISSUE THREAD

**Issue by juniorsysadmin** [voxpupuli/puppet-rabbitmq#717]
garethr/erlang is currently stale. Docs reference it. Sadly, other erlang modules on the Forge seem stale as well.

Reliance on garethr/erlang causes all Beaker acceptance tests to fail.

**Comment by wyardley** [comment]
Agreed - the docs should probably be updated completely. When I've done some basic testing, I've ended up using other methods to satisfy the erlang dep.

I'm not sure how useful an erlang module would be - if someone wanted to take a stab at updating it to make it useful, I'm guessing @garethr might be willing to have Voxpupuli take over the erlang module?

**Comment by wyardley** [comment]
> is the erlang module required on centos 7 as well, or only on centos6?

Not 100% sure from memory.
For newer versions of RabbitMQ, IIRC, I actually didn't have any luck with either garethr/erlang _or_ epel, and had to do some manual work to get things going (this doesn't affect the acceptance tests as they are today, but would be an issue for actual users of the module).

If it helps, here are the RMQ docs on the 3 ways to satisfy the erlang dep:
https://www.rabbitmq.com/install-rpm.html#install-erlang

I _believe_ the RabbitMQ provided packages are available via their repos.

I don't really have the time to work out a fix, but maybe Vox should adopt the erlang module and update it?

**Comment by wyardley** [comment]
I think the beaker issue is fixed, however, there are probably still improvements to be made around the docs, as well as figuring out the best way to satisfy the erlang dependency.

**Comment by dhoppe** [comment]
At the moment it is not possible to install RabbitMQ 3.7.x, because the dependencies for Erlang are not met. 

The module ```garethr/erlang``` is still referenced at ```.fixtures.yml``` and ```spec/acceptance/*.rb```. I am not sure if we really need this, since Bintray provides Erlang packages as ```.deb``` and ```.rpm```.

**Comment by wyardley** [comment]
Yeah, I’m not sure if there’s one size fits all Erlang, but for sure that module is old and doesn’t work anymore.

Until / unless the module default changes back to having `repos_ensure` as default, probably the vendor provided packages should be tested in integration test, tho if we had one for each case, that would be even better.

**Comment by wyardley** [comment]
Can close this now that #955 has shipped
