### ISSUE TITLE
Package cloud APT GPG key changed?

### ISSUE THREAD

**Issue by Mezzle** [voxpupuli/puppet-rabbitmq#742]
## Affected Puppet, Ruby, OS and module versions/distributions

- Distribution: Ubuntu/Debian

## How to reproduce (e.g Puppet code you use)

Attempt to install rabbitmq-server using apt method 

## What are you seeing

Failure to validate APT gpg key as it's not available

## What behaviour did you expect instead

Installation of rabbitmq-server

## Any additional information you'd like to impart

Our internal overnight build failed last night.  After investigation, this is due to the fact that the GPG key listed in https://github.com/voxpupuli/puppet-rabbitmq/blob/master/manifests/repo/apt.pp is no longer the relevant key for the archive.

Having investigated, it seems that the key needed is `8C695B0219AFDEB04A058ED8F4E789204D206F89`

I've found this via

```
 % wget https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey -qO - | gpg              
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2018-10-08 [SCEA]
      8C695B0219AFDEB04A058ED8F4E789204D206F89
uid           https://packagecloud.io/rabbitmq/rabbitmq-server (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>
sub   rsa4096 2018-10-08 [SEA]
```

I will make a new PR to update this, however, it seems that this should be checked to see if this is a security issue?  Changing the key - (and not having that key available in public keyservers) seems like a MAJOR security issue ?

**Comment by Mezzle** [comment]
Seems that this is due to the Package Cloud migration as mentioned at

https://www.rabbitmq.com/signatures.html#package-cloud

**Comment by wyardley** [comment]
There have been some discussions about the best / safest way to handle GPG keys in modules. I don't think anyone would argue that the current way is ideal.

re: public key servers, I think anyone can submit a key to the public keyservers, so if we prefer that source, I think that should be feasible too.

**Comment by jarro2783** [comment]
Package cloud has their own puppet module, so should rabbitmq just use that instead?

**Comment by wyardley** [comment]
I think I looked at that module when I was setting the stuff up and there was a reason I didn’t use it, but don’t remember what it was now.
