### ISSUE TITLE
admin_enable - controles both rabbitmq_management plugin and install of rabbitmqadmin

### ISSUE THREAD

**Issue by hjensas** [voxpupuli/puppet-rabbitmq#775]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.6
- Ruby: 2.0.0.648
- Distribution: CentOS 7 / RDO Openstack
- Module version: 8.2.3-rc0

## How to reproduce (e.g Puppet code you use)
Set parameter admin_enable: false

## What are you seeing
rabbitmqadmin script is not installed.
rabbitmq_management plug-in is not loaded/enabled.
rabbitmq.config has no configuration for the management api.

## What behaviour did you expect instead
The installation of rabbitmqadmin and enabling rabbitmq_management plugin should be separate.
The rabbitmqadmins script/program is a client tool, it can be installed on any workstation and used to manage any remote rabbitmq server/cluster with the rabbitmq_management plug-in enabled.

It should be possible to set up the rabbitmq server with the management API enabled, without also downloading and installing the client to use it.
Bonus: It should also be possible to only install the rabbitmqadmin client without also installing rabbitmq server.

## Output log
N/A

**Comment by bastelfreak** [comment]
Hi @hjensas, thanks for bringing this up. Are you able to provide a PR for this?

**Comment by hjensas** [comment]
I'm working on something. Will do some testing and then provide a PR.
