### ISSUE TITLE
Packagecloud Apt Pin is hardcoded 

### ISSUE THREAD

**Issue by func0der** [voxpupuli/puppet-rabbitmq#779]
Here: https://github.com/voxpupuli/puppet-rabbitmq/blob/48e8723c55d019ad419a7430700d034a6843fa6a/manifests/repo/apt.pp#L40

you are pinning packagecloud.io.
`rabbitmq::repo::apt::location` is changable though and could be any repository.

This seems to be broken since day one, back when rabbitmq.com - Repositories were used.

Please make the pin origin configurable, so one could use Bintray or other repositories.

**Comment by bastelfreak** [comment]
Hi @func0der, thanks for the issue. Are you able to provide a patch for this?
