### ISSUE TITLE
Puppet fails to run with an error "no parameter named 'download_options'"

### ISSUE THREAD

**Issue by alexizmailov** [voxpupuli/puppet-rabbitmq#790]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: v6.0.4
- Ruby: 2.5.0
- Distribution: CentOS Linux release 7.6.1810 (Core)
- Module version: v.9.0.0
- Archive module version: v.3.2.1 (latest)

## What are you seeing
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: 
no parameter named 'download_options' (file: /etc/puppetlabs/code/environments/rmq/modules/rabbitmq/manifests/install/rabbitmqadmin.pp, line: 47) 
on Archive[rabbitmqadmin] (file: /etc/puppetlabs/code/environments/rmq/modules/rabbitmq/manifests/install/rabbitmqadmin.pp, line: 47) on node int-mq-03.svc.int.ix.org.au
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
## What behaviour did you expect instead
Normal puppet run
## Output log

Provided higher

**Comment by wyardley** [comment]
@sammcj @alexizmailov: It is `download_options`:
https://github.com/voxpupuli/puppet-rabbitmq/blob/dd996ab9743df30cfdab16e6bd6b6796b77ee13a/manifests/install/rabbitmqadmin.pp#L59

which does seem to match current version of puppet-archive.
https://github.com/voxpupuli/puppet-archive/blob/56eedaf13617f1880ce5b1b268db53a774f453c1/README.md#download-customizations

So whatever is going on here, I don't think it has to do with the difference between option and options.

**Comment by alexizmailov** [comment]
Seems that [archive module](https://github.com/voxpupuli/puppet-archive/blob/master/manifests/init.pp) doesn't have this parameter in its puppet code:
```
class archive (
  Optional[String] $seven_zip_name     = $archive::params::seven_zip_name,
  Optional[String] $seven_zip_provider = $archive::params::seven_zip_provider,
  Optional[String] $seven_zip_source   = undef,
  Boolean          $aws_cli_install    = false,
```
However it is present in lib/puppet/type/archive.rb line 237:
```
  newparam(:download_options) do
    desc 'provider download options (affects curl, wget, and only s3 downloads for ruby provider)'

    validate do |val|
      unless val.is_a?(::String) || val.is_a?(::Array)
        raise ArgumentError, "download_options should be String or Array: #{val}"
      end
    end

    munge do |val|
      case val
      when ::String
        [val]
      else
        val
      end
    end
  end
```

**Comment by wyardley** [comment]
It’s in the providers (e.g., curl / wget):
https://github.com/voxpupuli/puppet-archive/tree/master/lib/puppet/provider/archive

**Comment by wyardley** [comment]
Just curious since I see the environments: do you use other archive versions in other Puppet environments? Because there’s a bug with this that’s caused problems in the past.

**Comment by alexizmailov** [comment]
Yes but I upgraded it in Production branch (sorry, it took a while - testing and such) and there is no difference in output. Puppet is still failing in the same way.

**Comment by wyardley** [comment]
You’re not using one of the other implementations in another env, like the camptocamp one?

**Comment by alexizmailov** [comment]
No, I'm using https://github.com/voxpupuli/puppet-archive

**Comment by Ordnaxz** [comment]
Same issue here, also using above archive module. Disabling above archive module does not fix the issue, commenting out "download_options" fixes it, but is of course not an acceptable workaround.

**Comment by eLvErDe** [comment]
Hello,

I'm having the same issue with puppet-archive 3.2.1

**Comment by wyardley** [comment]
@eLvErDe can you post a copy of your module tree (`puppet modules list` on the master should work in most cases, I think).

And same questions - are you using environments, and if so, do you have any of the other "puppet-archive" implementations installed anywhere?

**Comment by eLvErDe** [comment]
Hello,

I'm using two environments but atm the code in in sync. I can share the module list but I'd avoid publicly, can you share a private email ? acecile@letz-it.lu

**Comment by wyardley** [comment]
No response for quite some time. I don't think we can support getting the module list via email.
If you're still experiencing this issue, feel free to reopen or open a new issue.
