### ISSUE TITLE
no parameter named 'allow_insecure'

### ISSUE THREAD

**Issue by sreejithdivakar** [voxpupuli/puppet-rabbitmq#801]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.2
- Ruby: 2.0.0p648
- Distribution: CentOS Linux release 7.6.1810 (Core)
- Module version: v8.5.0

## What are you seeing
Puppet push fail with the following error.
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'allow_insecure' at /etc/puppetlabs/code/environments/production/modules/rabbitmq/manifests/install/rabbitmqadmin.pp:47 on Archive[rabbitmqadmin] at /etc/puppetlabs/code/environments/production/modules/rabbitmq/manifests/install/rabbitmqadmin.pp:47 on node iboss01-system04-n01-esy1.srv.symbionetworks.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

## What behaviour did you expect instead
'allow_insecure' parameter is already declared as shown below.
```puppet
    archive { 'rabbitmqadmin':
      path             => "${rabbitmq::rabbitmq_home}/rabbitmqadmin",
      source           => "${protocol}://${sanitized_ip}:${management_port}/cli/rabbitmqadmin",
      username         => $default_user,
      password         => $default_pass,
      allow_insecure   => true,  <<<<========
      download_options => $archive_options,
      cleanup          => false,
      require          => [
        Class['rabbitmq::service'],
        Rabbitmq_plugin['rabbitmq_management']
      ],
    }
```

**Comment by dhoppe** [comment]
@sreejithdivakar Could you please provide a code example from your role/profile? I do not know how you implemented this nodule and as you already mentioned, the parameter ```allow_insecure``` is  set and can not be changed.

**Comment by wyardley** [comment]
What version and source of puppet archive module are you using, and do you have multiple versions of it installed in different Puppet environments?

**Comment by sreejithdivakar** [comment]
Hi @dhoppe,

Thanks for your response to my query. I am not an expert in puppet. Please excuse if the below code is not what you are expecting.

Code example is as shown below.

class profile::xxxxx::symbiosys {

  include erlang
  class { 'rabbitmq': 
        repos_ensure => true,
        }
}

Also from the puppet master, when I execute the command --> puppet module list, archive module is listed as "invalid" as shown below.

├── puppet-archive (v2.1.0)  invalid

Rabbitmq module is showing as below.

├── puppet-rabbitmq (v8.5.0)


Thanks in advance
Sreejith

**Comment by sreejithdivakar** [comment]
Hi @wyardley 

Thanks for your response to my query. I am not an expert in puppet.

Version of puppet-archive module is 2.1.0

Would be great if you can guide me to find whether multiple versions of this module is installed in different environments...

Thanks in advance
Sreejith

**Comment by wyardley** [comment]
Your version does fall under the supported version listed in `metadata.json`: https://github.com/voxpupuli/puppet-rabbitmq/blob/cc78a33d98defdf0ef796d98ceb35b811168db5e/metadata.json#L69
Updating might be one thing to try, if possible, though, but from a quick search, this parameter does seem to have been around for a while.

My guess is that you would know it if you also had the camptocamp archive module installed somewhere.

**Comment by sreejithdivakar** [comment]
Hi @wyardley 

Do you want me to try upgrading puppet-rabbitmq module to the latest version which is v9.0.0?

From the module list, I can see the below camptocamp modules in production environment.

├── camptocamp-kmod (v0.1.2)
├── camptocamp-systemd (v2.1.0)  invalid

Not sure why some of the modules are showing as "invalid" in our master server.

Appreciate your response
Regards
Sreejith

**Comment by wyardley** [comment]
I would try updating both rabbitmq and archive modules if you’re able to.

As best I can tell, invalid should mean that the version doesn’t satisfy the requirements of at least one module.

**Comment by sreejithdivakar** [comment]
Hi @wyardley 

I will try upgrading the modules to the latest version

Thanks in advance
Sreejith

**Comment by sreejithdivakar** [comment]
Hi @wyardley / @dhoppe 

Issue is fixed by one of my senior devops expert colleague.

Below shown are the module upgrades I did in our environment.

puppet/rabbitmq ==> upgraded from (v8.5.0) to (v9.0.0)

puppetlabs/stdlib (>= 4.13.1 < 6.0.0) ==> current version ==> (v4.22.0)

puppet/archive (>= 2.0.0 < 4.0.0) ==> upgraded from (v8.5.0) to (v9.0.0)
    puppetlabs-stdlib >= 4.13.1 < 6.0.0 ==> current version ==> (v4.22.0)

camptocamp/systemd (>= 2.1.0 < 3.0.0) ==> current version ==> (v2.1.0)
    puppetlabs-inifile >= 1.6.0 <4.0.0 ==> Upgraded from (v1.2.0) to v2.5.0    
    puppetlabs-stdlib >= 4.13.1 < 6.0.0 ==> current version ==> (v4.22.0) 

Below are the changes made to the profile:- 

class profile::xxxxx::symbiosys {

  **require archive  <<<==== ADDED**
  **Class['archive'] -> Class['rabbitmq'] <<<==== ADDED**
  include erlang
  class { 'rabbitmq': 
        repos_ensure => true,
        }
}

This changes ensures that the archive class is defined for the node, then rabbitmq is able to use the Archive type.

Thanks for all the support
Sreejith
