### ISSUE TITLE
breaks /etc/rabbitmq ownership under ubuntu

### ISSUE THREAD

**Issue by hadmut** [voxpupuli/puppet-rabbitmq#813]
Puppet: 5.4.0
    Ruby: 2.5.1
    Distribution: Ubuntu 18.04
    Module version: 9.1.0

I found that the puppet-rabbitmq does not work when used repeatedly under Ubuntu, since puppet-rabbitmq changes the ownership of /etc/rabbitmq to root, while under Ubuntu (although I agree that this is poor design) it is supposed to be rabbitmq.rabbitmq, since rabbitmq-plugins want's to write /etc/rabbitmq/enabled_plugins and needs to temporarily create /etc/rabbitmq/enabled_plugins.tmp, therefore needs write access to /etc/rabbitmq.

**Comment by skrussell** [comment]
I'm going to add my comments here, that this also happens on CentOS installs. I performed a clean manual install of rabbitmq 3.7.21 on a development node today, and then, when later running puppet to apply a configuration, I was surprised to see the following changes:
```
Notice: /Stage[main]/Rabbitmq::Config/File[/etc/rabbitmq]/group: group changed 'rabbitmq' to 'root' (corrective)
Notice: /Stage[main]/Rabbitmq::Config/File[/etc/rabbitmq]/mode: mode changed '2755' to '0755' (corrective)
```
Seems to me that this module is enforcing incorrect permissions now-a-days.
Version information:
```
Puppet: 5.5.17
Distro: CentOS Linux release 7.7.1908 (Core)
Module version: 9.1.0 (but also tried git master branch)

**Comment by wyardley** [comment]
I think there was one pass at fixing some of these permissions things, (maybe try #796)? I think that one still needs some adjustments to work properly.

**Comment by wyardley** [comment]
Sorry for the delay, but hope the fix above will help. If you’re able, please test this off of master and let us know how it goes.
