### ISSUE TITLE
Add support for RHEL/CentOS 8

### ISSUE THREAD

**Issue by siebrand** [voxpupuli/puppet-rabbitmq#816]
The module is currently not supported on RHEL/CentOS 8. Please add support for those os versions.

**Comment by wyardley** [comment]
Are you able to make a PR to add or test this functionality?

**Comment by siebrand** [comment]
As far as I can tell, it would be as easy as adding version 8 to RHEL/CentOS in metadata.json. No way for me to prove this yet, though.

**Comment by wyardley** [comment]
If you can test / verify that it functions as-is, without any additional code changes, feel free to PR that. We'll need to make sure that it gets auto-added to the travis matrix just from that change so that at least acceptance tests are being run there.

**Comment by rehan2908** [comment]
When will the support for Centos 8 be added. Erlang Repo URL needs to be changed then

**Comment by timmooney** [comment]
What's the blocker on this issue?

RHEL 8 is about half way through its lifecycle, and RHEL 9 has been out for more than a year.

FYI I'm using puppet-rabbitmq 12.1.0 on RHEL 9.1 with puppet 6.x (which is also now EOL) and as far as I can tell it's working just fine.

**Comment by wyardley** [comment]
Hi - the blocker really relates to integration tests and some of the issues with bootstrapping erlang, as well as the discussions around switching back to having the RabbitMQ built packages as default again (with the default of `repos_ensure`).

I agree that it should probably work, esp. with the right settings around getting erlang setup and choosing which rabbitmq package to get.

But, someone will probably need to take it on themselves to make one or more PRs to get some of the above working before Vox can "officially" support those versions (and test them properly in CI)
