### ISSUE TITLE
rabbitmq should not install the latest version by default

### ISSUE THREAD

**Issue by bodepd** [voxpupuli/puppet-rabbitmq#82]
Currently, the rabbitmq module always adds rabbitmq repos from upstream. This means that the module will always install the latest version of the rabbitmq.

This is problematic for the following reasons:
- This will cause the module to not work at times (when a new major version is released).
- It does not allow users of this module to use the version of rabbitmq provided by their distro (in fact, it is not even possible to configure this module to not use the latest version)

**Comment by wyardley** [comment]
I think this is no longer an issue with how repos and versioning are now managed.
