### ISSUE TITLE
About RabbitMQ-Server Version Selection

### ISSUE THREAD

**Issue by espala** [voxpupuli/puppet-rabbitmq#822]
Hello Everybody,

I want to keep the version fixed. However, there is no version parameter.

For example, I installed "3.8.2-1.el7" version with epel.

I don't know if an update will come tomorrow, "3.8.2-9.el7" or "3.9.2-1.el7". I don't want it to make minor or major version changes automatically.

Because any changes can corrupt my system.

Maybe I'm missing something. Because such a large community should be able to choose the version we want in the module managed.  If there is such a possibility, I surely miss something. But if this is not the case, isn't that a risk?

Do you have any advice for me ?

**## Puppetserver Information ##**

> puppetserver version => 6.11.1
> 
> puppet module list |grep rabbit
> ├── puppet-rabbitmq (v10.0.0)

**## Client Information ##**

> yum list installed |grep "erlang\|socat\|rabbitmq"
> erlang.x86_64                          22.2-1.el7                      installed
> socat.x86_64                           1.7.3.2-2.el7                   @base
> rabbitmq-server.noarch                 3.8.2-1.el7                     @rabbitmq_rabbitmq-server
> 
> cat /etc/redhat-release
> CentOS Linux release 7.7.1908 (Core)

**my epel rpm,**
`http://mirror.centos.org/centos/7/extras/x86_64/Packages/epel-release-7-11.noarch.rpm`

**my erlang rpm,**
`rpm -ivh https://github.com/rabbitmq/erlang-rpm/releases/download/v22.2/erlang-22.2-1.el7.x86_64.rpm`

**## My manifest ##**
```
...
class { 'rabbitmq':
  port => 5672,
  delete_guest_user => true,
  admin_enable => true,
  repos_ensure => true,

  config_cluster => true,
  cluster_nodes => ['example01','example02','example03'],
  cluster_node_type => 'disc',
  erlang_cookie => 'examplecookie',
  wipe_db_on_cookie_change => true,
}
...
```

**Comment by wyardley** [comment]
This could be documented better, but have you tried setting `$package_ensure` to the version you want?

**Comment by wyardley** [comment]
@espala did that work for you?
