### ISSUE TITLE
Rabbitmq_user seems to be failing

### ISSUE THREAD

**Issue by jake2184** [voxpupuli/puppet-rabbitmq#827]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.8.1
- Ruby: 2.5.3
- Distribution: Centos 7.7
- Module version: 9.1.0

## How to reproduce (e.g Puppet code you use)
`puppet resource rabbitmq_user --debug`
or 
`  rabbitmq_user {
        'admin':
            admin    => true,
            password => 'admin'
    }`

## What are you seeing
```
[root@hostname ~]# puppet resource rabbitmq_user --debug
Debug: Runtime environment: puppet_version=6.8.1, ruby_version=2.5.3, run_mode=user, default_encoding=UTF-8
Debug: Evicting cache entry for environment 'production'
Debug: Deleted text domain :production: false
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Executing: '/sbin/rabbitmqctl -q status'
Error: Could not run: undefined method 'scan' for nil:NilClass
```
or
```
Debug: Executing: '/usr/bin/systemctl is-active rabbitmq-server'
Debug: Executing: '/usr/bin/systemctl is-enabled rabbitmq-server'
Debug: Prefetching rabbitmqctl resources for rabbitmq_user
Debug: Executing: '/sbin/rabbitmqctl -q status'
Error: Could not prefetch rabbitmq_user provider 'rabbitmqctl': undefined method `scan' for nil:NilClass
Debug: Storing state
Debug: Pruned old state cache entries in 0.00 seconds
Debug: Stored state in 0.11 seconds
Error: Failed to apply catalog: undefined method `scan' for nil:NilClass

```
## What behaviour did you expect instead
rabbitmq_user resource to work

## Any additional information you'd like to impart
I cannot find (or know that I am looking at) relevant code within this module, or any use of a scan function.

**Comment by jake2184** [comment]
I'm also getting similar errors for `rabbitmq_plugin`. 
```
[root@hostname ~]# puppet resource rabbitmq_plugin --debug
Debug: Runtime environment: puppet_version=6.8.1, ruby_version=2.5.3, run_mode=user, default_encoding=UTF-8
Debug: Evicting cache entry for environment 'production'
Debug: Deleted text domain :production: false
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Executing: '/sbin/rabbitmq-plugins list -E -m'
Debug: Command succeeded
Error: Could not run: Cannot parse invalid plugins line: Listing plugins with pattern ".*" ...
[root@hostname ~]# /sbin/rabbitmq-plugins list -E -m
Listing plugins with pattern ".*" ...
rabbitmq_auth_backend_ldap
rabbitmq_management
rabbitmq_stomp
```

This looks like it might be a change in the rabbitmq commands? I'm running rabbitmq-3.8.2, and looking at the README it looks like this module has only been tested/supports up to 3.6. If that's confirmed to be the case then I guess this is a feature request rather than a big report.

**Comment by wyardley** [comment]
Can you try with 10.x?

**Comment by jake2184** [comment]
Yes, 10.0.0 works fine.

Sorry, I really should have tried that before raising a ticket.

**Comment by wyardley** [comment]
No worries. As you say, it’s still not listed as supported, partially because we don’t yet integration test the newer version. However some fixes to support it did go out with the last release.
