### ISSUE TITLE
Not idempotent again on RHEL based platforms since move to systemd module

### ISSUE THREAD

**Issue by tobias-urdin** [voxpupuli/puppet-rabbitmq#836]
This commit [1] some years ago fixed so that this module on RHEL based platforms was idempotent again. Since the move to the systemd module the same issue has occured again.

Need to implement a way to set selinux_ignore_defaults in systemd::service_limits (and thus in systemd::dropin_file) and add that usage in this module.

[1] https://github.com/voxpupuli/puppet-rabbitmq/commit/0227f762070ffbbea3c28d6a60174de98fa4cc1c

**Comment by tobias-urdin** [comment]
On CentOS 8:
2020-05-29 10:52:28 +0000 /Stage[main]/Rabbitmq::Config/Systemd::Service_limits[rabbitmq-server.service]/Systemd::Dropin_file[rabbitmq-server.service-90-limits.conf]/File[/etc/systemd/system/rabbitmq-server.service.d]/seltype (notice): seltype changed 'rabbitmq_unit_file_t' to 'systemd_unit_file_t'

**Comment by tobias-urdin** [comment]
Adding support for selinux_ignore_defaults to systemd module here [1].

[1] https://github.com/camptocamp/puppet-systemd/pull/151

**Comment by tobias-urdin** [comment]
We can then edit this line [1] in this module and add the selinux_ignore_defaults parameter for the systemd::service_limits usage when handling RHEL based operating systems.

[1] https://github.com/voxpupuli/puppet-rabbitmq/blob/master/manifests/config.pp#L234

**Comment by adeleglise** [comment]
Is it possible that this commit added a breaking change ?

I can observe this error when trying to use the module v11.0.0 on a Ubuntu 20.04 box:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Systemd::Service_limits[rabbitmq-server.service]: has no parameter named 'selinux_ignore_defaults' (file: /etc/puppetlabs/code/environments/staging/modules/rabbitmq/manifests/config.pp, line: 236) on node
```

**Comment by wyardley** [comment]
@adeleglise can you see if you have a version of the systemd module that’s in bounds of the lower bound that the module requests? Whether this new parameter being required should have been a breaking change I can’t say (I would lean towards no), but feel free to open a new issue if you see this error even with the updated version of the systemd module.

Sometimes, I’ve seen quirks with caching when using environments and multiple versions of the same module, so may want to see if you have other modules that also require puppet-systemd

**Comment by tobias-urdin** [comment]
Verify that you have the proper puppet-systemd module.

```
    {
      "name": "camptocamp/systemd",	      "name": "camptocamp/systemd",
      "version_requirement": ">= 2.1.0 < 3.0.0"	      "version_requirement": ">= 2.10.0 < 3.0.0"
    }
```

**Comment by adeleglise** [comment]
I have the module `mod 'camptocamp-systemd', '2.5.1'`. 

Sorry, I saw that this module is not listed to be compatible with ubuntu 20.04. Maybe that's my issue.
