### ISSUE TITLE
Not compatible with latest puppet-systemd

### ISSUE THREAD

**Issue by karelyatin** [voxpupuli/puppet-rabbitmq#875]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.21.1
- Ruby: 2.5
- Distribution: CentOS8
- Module version: Latest puppet-rabbitmq commit

## How to reproduce (e.g Puppet code you use)
with latest puppet-systemd commit issue should be seen as the removed class is being used in puppet-rabbitmq https://github.com/voxpupuli/puppet-rabbitmq/blob/7f806ac6983ec8d087a2c9e86b4e1467198d6981/manifests/service.pp#L26-L28

## What are you seeing
Could not find resource 'Class[Systemd::Systemctl::Daemon_reload]' for relationship on 'Service[rabbitmq-server]' 

## What behaviour did you expect instead
It should be made compatible with latest puppet-systemd(no tag released yet). We test latest commits and hit the issue for now we have pinned puppet-systemd on our side https://review.rdoproject.org/r/#/c/32088/.

## Output log
https://logserver.rdoproject.org/ci.centos.org/weirdo-generic-packstack-scenario001/12896/weirdo-project/logs/latest/manifests/192.168.1.213_controller.pp.log.txt.gz

## Any additional information you'd like to impart
https://github.com/camptocamp/puppet-systemd/commit/97dd16fa32886b5b0f77a6f38a4953d4c1511c0e dropped support for puppet 4 and 5 as they are EOL, and removed Systemd::Systemctl::Daemon_reload with reasoning that it's not needed with puppet6.

**Comment by wyardley** [comment]
Hello:

https://github.com/camptocamp/puppet-systemd/pull/171 Is flagged as backwards compatible, and metadata requires <3.0 (https://github.com/voxpupuli/puppet-rabbitmq/blob/dfd7607753b1fe4a4ad1de41eb31183d1a23dca8/metadata.json#L71) also, this module’s metadata still lists Puppet 5 as supported, so I don’t think this is breaking as-is.

When those versions are updated, some changes may need to be made, but I don’t see huge urgency to rush to drop support and force people to take the newer systemd module yet, though PRs are accepted.
