### ISSUE TITLE
Compatibility with puppet-systemd

### ISSUE THREAD

**Issue by rhandimartin** [voxpupuli/puppet-rabbitmq#898]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.x
- Ruby: 2.x
- Distribution: RedHat, Debian
- Module version: 11.1.0

## What are you seeing

The systemd dependency stil refers to the camptocamp version. Currently, module is puppet-systemd 3.x branch. I see that the 11.1.0 of rabbitmq is still calling Class['systemd::systemctl::daemon_reload'] which was still present in puppet-systemd 2.x branch... Are there any plans to bring rabbitmq module up to compat with later versions of systemd?

**Comment by kenyon** [comment]
#885

**Comment by wyardley** [comment]
It doesn't seem like those conflicts got resolved; if someone wants to cherry-pick it (with original attribution) and resolve conflicts as a new PR, I can take a look at it.

**Comment by timmooney** [comment]
Is this issue still relevant?

puppet-rabbitmq-12.1.0 ships with puppet/systemd (not camptocamp/systemd) as the dependency and appears to only call the relevant class if it's defined.  I'm using puppet-systemd-3.10.0, where systemd::systemctl::daemon_reload is no longer defined, and things seem to be working just fine.
