### ISSUE TITLE
need support for newer versions of dependency puppet-archive

### ISSUE THREAD

**Issue by timmooney** [voxpupuli/puppet-rabbitmq#902]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: OpenSource, puppetserver 6.18.0
- Ruby: whatever version is included with puppetserver 6.18.0
- Distribution: RHEL 7
- Module version: 11.1.0

## How to reproduce (e.g Puppet code you use)

Install puppet-rabbitmq 11.1.0 (current latest).

## What are you seeing

```shell
$ sudo puppet module upgrade puppet-archive
Notice: Preparing to upgrade 'puppet-archive' ...
Notice: Found 'puppet-archive' (v4.6.0) in /etc/puppetlabs/code/environments/production/forge-modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not upgrade module 'puppet-archive' (v4.6.0 -> latest)
  There are 4 newer versions
    No combination of dependency upgrades would satisfy all dependencies
    Dependencies will not be automatically upgraded across major versions
    Upgrading one or more of these modules may permit the upgrade to succeed:
    - puppetlabs-stdlib
    Use `puppet module upgrade --force` to upgrade only this module
```

Note that `puppet module` is wrong, it's not `puppetlabs-stdlib` that's blocking the upgrade of `puppet-archive`, it's `puppet-rabbitmq`:

```shell
$ grep -B 1 -A 2 puppet/archive rabbitmq/metadata.json
    {
      "name": "puppet/archive",
      "version_requirement": ">= 2.0.0 < 6.0.0"
    },
```

## What behaviour did you expect instead

_Expect_ is too strong of a word here; what I'm hoping is that `puppet-rabbitmq` will soon add support for newer `puppet-archive` (and `puppet-systemd`, for that matter).

## Any additional information you'd like to impart

Thanks for `puppet-rabbitmq`!  It's very useful.

**Comment by root-expert** [comment]
Fixed in 12.0.0 release
