### ISSUE TITLE
why do you use RabbitMQ

### ISSUE THREAD

**Issue by HoangNgo88** [voxpupuli/puppet-rabbitmq#920]
Hi, I am reading your project and I love this project
I have a question, why do you choose RabbitMQ in your project instead of others like ZeroMQ or Kafka, are there any special features but others dont have it. Can you share me  it. I am wondering when I should choose RabbitMQ instead of others like ZeroMQ or Kafka

**Comment by kenyon** [comment]
This is a Puppet module for managing RabbitMQ.
