### ISSUE TITLE
Question: Will support be added for Puppet 8 and RHEL8?

### ISSUE THREAD

**Issue by maureen-lawless** [voxpupuli/puppet-rabbitmq#942]
Hi,

I'd like to know if support will be added in the future for:

1. Puppet 8
2. RedHat 8

If yes, what would the expected timeline be?

Thanks,
Maureen

**Comment by wyardley** [comment]
Looks like #938 (not yet released) added puppet 8 support. As far as RHEL, if you don’t know what changes to make, I can take a pass at adding that support, depending on how much work is involved - if tests pass without additional code changes, shouldn’t be that hard

**Comment by wyardley** [comment]
It may not work until someone implements the stuff started in #926 -- looks like using the default vendor repos, no `rabbitmq-server` package is available.

**Comment by wyardley** [comment]
That said, my guess is that it will work, at least with `repos_ensure` set to `true` -- you just may have to ignore the metadata warnings.

**Comment by wyardley** [comment]
So, Puppet 8 is now properly supported (it was supported in metadata before, but fixed properly in #985

I'm not sure about RHEL 8 / CentOS 8. Looks like RHEL 8 is EOL at the end of the month, and CentOS 8 already was EOL in 2021 or something, but if it's trivial, we can see if official support can be added for a release or two and then dropped.

**Comment by wyardley** [comment]
Closing in favor of #816
