### ISSUE TITLE
Policy "applyto" options missing

### ISSUE THREAD

**Issue by jimmybigcommerce** [voxpupuli/puppet-rabbitmq#947]
https://github.com/voxpupuli/puppet-rabbitmq/blob/ba728f5d3317117bb96de6895535d5965ca05c43/REFERENCE.md?plain=1#L1776-L1782

Currently this module only support the following options for the policy `applyto` option:
```
##### `applyto`

Valid values: `all`, `exchanges`, `queues`
```

However, RabbitMQ itself supports:
```
all, exchanges, queues, classic_queues, quorum_queues, streams
```

It would be great if this module supported these also

**Comment by wyardley** [comment]
I've taken a pass at this in #948

**Comment by jimmybigcommerce** [comment]
Amazing @wyardley - greatly appreciated!
