### ISSUE TITLE
Missing support for Vhost Metadata

### ISSUE THREAD

**Issue by jimmybigcommerce** [voxpupuli/puppet-rabbitmq#963]
The module doesn't support defining/updating metadata for VHosts. This will be needed to set the default queue type to Quorum Queues on a Vhost.

![image](https://github.com/voxpupuli/puppet-rabbitmq/assets/52940257/73656b7c-caad-4dcb-b4b7-4d54434d4121)

**Comment by jimmybigcommerce** [comment]
@wyardley I thought I might take a stab at this. How do you feel about this syntax?
```
     rabbitmq_vhost { 'myvhost':
       ensure     => present,
       metadata => {
        'description'               => 'myvhost description',
        'default_queue_type' => 'quorum',
        'tags'                          => 'myvhost tags',
       }
     }
```

**Comment by wyardley** [comment]
Maybe get some other feedback too, but my high level thought is that maybe some or all of these should be first class params vs in a `metadata` hash? in particular, with `tags`, there seems to be a pattern of having a `tags` list for some resource types which I _think_ are roughly analagous, e.g.,

**Comment by jimmybigcommerce** [comment]
That works for me. Is there anyone specific you suggest I should ask for feedback>

**Comment by jimmybigcommerce** [comment]
The other question is should we make quorum queues the default queue type if not specified. Currently RMQ defaults to Classic Queues, but these will be removed in RMQ 4 so does it make more sense to make it the default in the module now. Or do a version check to decide which to use as default?

**Comment by wyardley** [comment]
> That works for me. Is there anyone specific you suggest I should ask for feedback

The `#voxpupuli` on the Puppet Slack or Vox's IRC channel would probably be good places to get opinions (or help), or you could see if @ekohl wants to weigh in.

I would also definitely suggest getting the integration tests working locally in Docker if at all possible - it'll really help testing / iteration, as well as making sure that your acceptance tests more or less work before you push up. You can spin up the test with `BEAKER_destroy=no` and exec in after it's done and then use that to try different stuff.

> Or do a version check to decide which to use as default?

I _think_ Vox typically tries to keep behavior consistent within the module within reason (vs. tying default behavior to the RMQ version). There's still a quite of bit of work to do anyway if this module is ever going to properly ship with RMQ 4.x by default (or, probably, even support it), so, with the caveat that I haven't used RMQ or Puppet for quite some number of years, I would say use classic as the default, and if / when the default behavior changes, ideally, update the default along with that (or update as another breaking change). But it's not a strong preference from my end.
