### ISSUE TITLE
puppet-archive version

### ISSUE THREAD

**Issue by sandwitch** [voxpupuli/puppet-rabbitmq#965]
Is it possible to bump the puppet-archive version to 7.1.0. Should i create a pull request?

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

**Comment by wyardley** [comment]
I think it will run into the same issues as #952

**Comment by sandwitch** [comment]
So we wait till https://github.com/voxpupuli/puppet-systemd/commit/16962d9138091636391591f623e0241de5eeda67 hits the forge?
