### ISSUE TITLE
could not find class ::epel when upgrading to 13.4.0

### ISSUE THREAD

**Issue by jplindquist** [voxpupuli/puppet-rabbitmq#995]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7
- Distribution: CentOS 7
- Module version: 13.4.0

## How to reproduce (e.g Puppet code you use)

```
class { 'rabbitmq': }
```

## What are you seeing
We're not setting `repos_ensure` and defaults to `false` still , so we were not expecting any repo management by the module. When upgrading to the latest version it seems to have a hard requirement on the `epel` module when we're already managing repositories outside of this. Is it possible to make this optional still so that `repos_ensure` or possibly some new option like` manage_repos` supersedes it entirely, and does not perform any repo management when it is not necessary?  For example, we are running on CentOS 7 but pulling packages from packagecloud

## What behaviour did you expect instead
No errors when not expecting to have any repos managed by the rabbitmq module, or managing repos externally

## Output log
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::epel for testrmq.example.com (file: /etc/puppetlabs/code/puppet-control/production/modules/rabbitmq/manifests/init.pp, line: 511, column: 5) on node testrmq.example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by wyardley** [comment]
Hi, that’s a good call. We could make it a soft dependency again (and just document it / include in the integration test), or maybe make  flag to disable it. @bastelfreak - what’s your take here? Are you able to add an adjustment to support this use case?

I believe this was added in #983

**Comment by jplindquist** [comment]
Thanks!  Either way works for me, a soft dependency or another option to disable repo management would be a good path forward I think.

**Comment by wyardley** [comment]
Apologies this wasn’t flagged as breaking.

It’s possible we may have toble

**Comment by wyardley** [comment]
Apologies this wasn’t flagged as breaking.

It’s possible we may have toble

**Comment by wyardley** [comment]
@bastelfreak @ekohl @TheMeier: I threw up two options for how we could possibly resolve this; willing to rework either.
